version = 0.1

[default.global.parameters]
stack_name = "game-stack"
region = "us-east-2"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = false

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true
template_file = "/home/max/code/photogame/backend/template.yaml"
dependency_layer = false
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xi4qigaoxhza"

  [default.sync.parameters.parameter_overrides]
GameStateMachineName = "GameLogic"
StageName = "Staging"
GameBucketName = "game-photo-bucket"

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
